### ISSUE TITLE
Characters cannot equip rings without weapons in battle

### ISSUE THREAD

**Issue by xenometal** [ShiningForceCentral/SF2DISASM#19]
### Overview ###
The game seemingly enters an infinite loop at some point during "after turn" processing if a ring was equipped while no having a weapon equipped.

https://github.com/ShiningForceCentral/SF2DISASM/assets/2898219/f1dc9abe-9b2c-49be-97b1-f7db75fb6025

**Comment by Slegar-sf2** [comment]
maybe we need to move the moveq function #1,d2 down ?

```ApplyAfterTurnRecovery:
                
                movem.l d1-d6/a0,-(sp)
                move.w  d0,((TEXT_NAME_INDEX_1-$1000000)).w
                clr.w   d5                  ; d5.w = recovery amount
                jsr     GetEquippedRing
                move.w  d1,d4               ; d4.w = copy of equipped ring
                jsr     GetEquippedWeapon
                move.w  d1,d3               ; d3.w = copy of equipped weapon
                moveq   #1,d2```

**Comment by xenometal** [comment]
The `moveq   #1,d2 ` instruction definitely needed to be moved down, because both the GetEquippedRing and GetEquippedWeapon routines return a value in d2.

I'm going to close the issue for now, but feel free to reopen it by leaving a comment if that didn't fix it.
