### ISSUE TITLE
Cube driver possibly modified

### ISSUE THREAD

**Issue by DevonArtmeier** [ShiningForceCentral/SF2DISASM#2]
I've been dissecting Dr. Robotnik's Mean Bean Machine, another game with the Cube sound driver. I noticed that in that game, there is no FM6 support. In the place of the DAC disable flag for music is a word-sized value that indicates how long it takes before the driver fades out the song from the moment it starts playing it.

Makes me wonder if Shining Force 2's version of the driver is modified to remove the fade out time thing, add in that flag, but keep that unused byte so that the format doesn't get shifted around.

**Comment by wizardwhosaysni** [comment]
Hey,

Here's some very old documentation I made back in 2008 :
https://github.com/ShiningForceCentral/SF2DISASM/blob/master/disasm/data/sound/musicbanks.txt

Indeed I see that the byte following the DAC flag is always zero in SF2s version of Cube. The assumption I made back then probably doesn't make much sense now that you mention this word usage for Mean Bean.

So anyway yes, the format's structure was kept intact by leaving the remaining byte unused. :)
